RDD:
  LAMBDA_GEO: 0.01
  DESCRIPTOR:
    BACKBONE: mobilenet_v3_large
    USE_22K: false
    USE_DEFORMABLE_TRANSFORMER: true
    NUM_FEATURE_LEVELS: 5
    PRETRAIN_BACKBONE: true
    USE_CANONICAL_DESCRIPTOR: true
    GEOMETRY_START_EPOCH: 5
    CANONICAL_GRID_SIZE: 16
    CANONICAL_RADIUS: 8.0
    CANONICAL_PADDING_MODE: border
    CANONICAL_ALIGN_CORNERS: false
    GEOMETRY_HEAD_HIDDEN_DIM: 128
    GEOMETRY_JACOBIAN_EPS: 1.0
