RDD:
  DESCRIPTOR:
    BACKBONE: resnet_50
    USE_22K: false
    USE_DEFORMABLE_TRANSFORMER: false
    DESCRIPTOR_STAGE: 2
    LOGVAR_MIN: -6.0
    LOGVAR_MAX: 6.0
    LAMBDA_SIGMA: 0.001
    LAMBDA_REC: 0.0
    PROBABILISTIC_NORMALIZE_MU: true
    PROBABILISTIC_CHUNK_SIZE: 64
    PROBABILISTIC_MAX_PAIRS: 2048
    NUM_FEATURE_LEVELS: 5
    PRETRAIN_BACKBONE: true
  DETECTOR:
    TYPE: shared_descriptor
    INPUT_DIM: 256
    UPSAMPLE_DIMS: [128, 64]
